### ISSUE TITLE
Browsing LFG Tool.

### ISSUE THREAD

**Issue by j0hanSE** [HybridEidolon/LFGEnhanced#1]
Message: Interface\AddOns\LFGEnhanced\LFGEnhanced.lua:249: attempt to index local 'active_entry_info' (a nil value)
Time: Mon Sep  5 20:24:27 2022
Count: 2
Stack: Interface\AddOns\LFGEnhanced\LFGEnhanced.lua:249: attempt to index local 'active_entry_info' (a nil value)
[string "@Interface\SharedXML\SharedBasicControls.lua"]:356: in function <Interface\SharedXML\SharedBasicControls.lua:355>
[string "=[C]"]: ?
[string "@Interface\AddOns\LFGEnhanced\LFGEnhanced.lua"]:249: in function `handler'
[string "@Interface\AddOns\LFGEnhanced\LFGEnhanced.lua"]:229: in function <Interface\AddOns\LFGEnhanced\LFGEnhanced.lua:226>

Locals: errorMessage = "Interface\AddOns\LFGEnhanced\LFGEnhanced.lua:249: attempt to index local 'active_entry_info' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:339
MESSAGE_TYPE_ERROR = 0

**Comment by HybridEidolon** [comment]
Fixed in 44533f73defc0731bcdfc7ec1b964df470d0b41c
